In [1]:
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import TimeoutException, NoSuchElementException
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd

**1.Andhra Pradhesh**

In [3]:
df = pd.read_csv("AP.csv")
df

,Route_name,Route_link
0,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...
1,Vijayawada to Hyderabad,https://www.redbus.in/bus-tickets/vijayawada-t...
2,Hyderabad to Ongole,https://www.redbus.in/bus-tickets/hyderabad-to...
3,Kakinada to Visakhapatnam,https://www.redbus.in/bus-tickets/kakinada-to-...
4,Bangalore to Tirupati,https://www.redbus.in/bus-tickets/bangalore-to...
5,Bangalore to Kadapa,https://www.redbus.in/bus-tickets/bangalore-to...
6,Ongole to Hyderabad,https://www.redbus.in/bus-tickets/ongole-to-hy...
7,Kadapa to Bangalore,https://www.redbus.in/bus-tickets/kadapa-to-ba...
8,Chittoor (Andhra Pradesh) to Bangalore,https://www.redbus.in/bus-tickets/chittoor-and...
9,Visakhapatnam to Kakinada,https://www.redbus.in/bus-tickets/visakhapatna...
10,Bangalore to Anantapur (andhra pradesh),https://www.redbus.in/bus-tickets/bangalore-to...
11,Bangalore to Chittoor (Andhra Pradesh),https://www.redbus.in/bus-tickets/bangalore-to...
12,Anantapur (andhra pradesh) to Bangalore,https://www.redbus.in/bus-tickets/ananthapur-t...
13,Hyderabad to Kurnool,https://www.redbus.in/bus-tickets/hyderabad-to...
14,Tirupati to Bangalore,https://www.redbus.in/bus-tickets/tirupathi-to...
15,Narasaraopet to Hyderabad,https://www.redbus.in/bus-tickets/narsaraopet-...
16,Vinukonda to Hyderabad,https://www.redbus.in/bus-tickets/vinukonda-to...
17,Hyderabad to Vinukonda,https://www.redbus.in/bus-tickets/hyderabad-to...
18,Visakhapatnam to Vijayawada,https://www.redbus.in/bus-tickets/visakhapatna...
19,Bangalore to Rayachoti,https://www.redbus.in/bus-tickets/bangalore-to...
20,Hyderabad to Guntur (Andhra Pradesh),https://www.redbus.in/bus-tickets/hyderabad-to...
21,Guntur (Andhra Pradesh) to Hyderabad,https://www.redbus.in/bus-tickets/guntur-to-hy...
22,Hyderabad to Eluru,https://www.redbus.in/bus-tickets/hyderabad-to...
23,Eluru to Hyderabad,https://www.redbus.in/bus-tickets/eluru-to-hyd...
24,Bangalore to Kadiri,https://www.redbus.in/bus-tickets/bangalore-to...
25,Madanapalli to Bangalore,https://www.redbus.in/bus-tickets/madanapalli-...
26,Bangalore to Madanapalli,https://www.redbus.in/bus-tickets/bangalore-to...
27,Macherla (andhra pradesh) to Hyderabad,https://www.redbus.in/bus-tickets/macherla-to-...
28,Rajahmundry to Visakhapatnam,https://www.redbus.in/bus-tickets/rajahmundry-...
29,Nandyal to Hyderabad,https://www.redbus.in/bus-tickets/nandyala-to-...
30,Rayachoti to Bangalore,https://www.redbus.in/bus-tickets/rayachoti-to...
31,Kurnool to Hyderabad,https://www.redbus.in/bus-tickets/kurnool-to-h...
32,Kadiri to Bangalore,https://www.redbus.in/bus-tickets/kadiri-to-ba...
33,Visakhapatnam to Rajahmundry,https://www.redbus.in/bus-tickets/visakhapatna...
34,Hyderabad to Addanki,https://www.redbus.in/bus-tickets/hyderabad-to...
35,Hyderabad to Anantapur (andhra pradesh),https://www.redbus.in/bus-tickets/hyderabad-to...
36,Hyderabad to Markapuram,https://www.redbus.in/bus-tickets/hyderabad-to...
37,Rajahmundry to Vijayawada,https://www.redbus.in/bus-tickets/rajahmundry-...
38,Tirupati to Chennai,https://www.redbus.in/bus-tickets/tirupathi-to...
39,Vijayawada to Visakhapatnam,https://www.redbus.in/bus-tickets/vijayawada-t...
40,Hyderabad to Macherla (andhra pradesh),https://www.redbus.in/bus-tickets/hyderabad-to...
41,Hyderabad to Rajahmundry,https://www.redbus.in/bus-tickets/hyderabad-to...
42,Chilakaluripet to Hyderabad,https://www.redbus.in/bus-tickets/chilakalurip...
43,Rajahmundry to Hyderabad,https://www.redbus.in/bus-tickets/rajahmundry-...
44,Kurnool to Bangalore,https://www.redbus.in/bus-tickets/kurnool-to-b...
45,Hyderabad to Nandyal,https://www.redbus.in/bus-tickets/hyderabad-to...

In [565]:
#retrive the bus details
driver_A = webdriver.Chrome()
Bus_names_A = []
Bus_types_A = []
Start_Time_A = []
End_Time_A = []
Ratings_A = []
Total_Duration_A = []
Prices_A = []
Seats_Available_A = []
Route_names_A = []
Route_links_A = []

driver_A.maximize_window()
for i,r in df.iterrows():
    link=r["Route_link"]
    routes=r["Route_name"]

# Loop through each link
    driver_A.get(link)
    time.sleep(6)  

    # Click on elements to reveal bus details
    elements = driver_A.find_elements(By.XPATH, f"//a[contains(@href, '{link}')]")
    #print("elements found")
    for element in elements:
        element.click()
        time.sleep(2)

    # click elements to views bus
    try:
        clicks = driver_A.find_element(By.XPATH, "//div[@class='button']")
        clicks.click()
        
    except:
        continue  
    time.sleep(2)
    
    number_of_scrolls = 25
    scroll_pause_time = 1  # Adjust this based on the page's loading time

    for _ in range(number_of_scrolls):
        # Scroll down to the bottom using JavaScript
        driver_A.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    
        # Wait for new content to load
        time.sleep(scroll_pause_time)
 

    # Extract bus details
    bus_name = driver_A.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
    bus_type = driver_A.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
    start_time = driver_A.find_elements(By.XPATH, "//*[@class='dp-time f-19 d-color f-bold']")
    end_time = driver_A.find_elements(By.XPATH, "//*[@class='bp-time f-19 d-color disp-Inline']")
    total_duration = driver_A.find_elements(By.XPATH, "//*[@class='dur l-color lh-24']")
    try:
        rating = driver_A.find_elements(By.XPATH,"//div[@class='clearfix row-one']/div[@class='column-six p-right-10 w-10 fl']")
    except:
        continue
    price = driver_A.find_elements(By.XPATH, '//*[@class="fare d-block"]')
    seats = driver_A.find_elements(By.XPATH, "//div[contains(@class, 'seat-left')]")

    # Append data to respective lists
    for bus in bus_name:
        Bus_names_A.append(bus.text)
        Route_links_A.append(link)
        Route_names_A.append(routes)
    for bus_type_elem in bus_type:
        Bus_types_A.append(bus_type_elem.text)
    for start_time_elem in start_time:
        Start_Time_A.append(start_time_elem.text)
    for end_time_elem in end_time:
        End_Time_A.append(end_time_elem.text)
    for total_duration_elem in total_duration:
        Total_Duration_A.append(total_duration_elem.text)
    for ratings in rating:
        Ratings_A.append(ratings.text)
    for price_elem in price:
        Prices_A.append(price_elem.text)
    for seats_elem in seats:
        Seats_Available_A.append(seats_elem.text)
        
print("Successfully Completed")

Successfully Completed

In [568]:
# from list to convert data frame
data_AP = {
    'Route_name': Route_names_A,
    'Route_link': Route_links_A,
    'Bus_name': Bus_names_A,
    'Bus_type': Bus_types_A,
    'Start_time': Start_Time_A,
    'Total_duration': Total_Duration_A,
    'End_time': End_Time_A,
    "Ratings": Ratings_A,
    'Price': Prices_A,
    "Seats_Available": Seats_Available_A
}

df_buses_AP = pd.DataFrame(data_AP)
#convert dataframe to csv
path=r"C:\Users\M Karan kumar\1JupyterNoteBOOk\REDBUS\buses_AP.csv"
df_buses_AP.to_csv(path,index=False)

In [570]:
df_buses_AP

,Route_name,Route_link,Bus_name,Bus_type,Start_time,Total_duration,End_time,Ratings,Price,Seats_Available
0,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,FRESHBUS,Electric A/C Seater (2+2),06:25,05h 20m,11:45,4.7\n396,374,25 Seats available
1,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,FRESHBUS,Electric A/C Seater (2+2),10:25,06h 35m,17:00,4.6\n352,374,39 Seats available
2,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,IntrCity SmartBus,AC Sleeper (2+1),23:30,07h 15m,06:45,4.7\n181,INR 639,31 Seats available
3,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,AdIntrCity SmartBus,A/C Seater / Sleeper (2+1),00:15,06h 10m,06:25,4.3\n246,INR 359,30 Seats available
4,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,FRESHBUS,Electric A/C Seater (2+2),23:20,06h 25m,05:45,4.5\n500,500,35 Seats available
...,...,...,...,...,...,...,...,...,...,...
721,Hyderabad to Nandyal,https://www.redbus.in/bus-tickets/hyderabad-to...,,,,,,,,
722,Hyderabad to Nandyal,https://www.redbus.in/bus-tickets/hyderabad-to...,,,,,,,,
723,Hyderabad to Nandyal,https://www.redbus.in/bus-tickets/hyderabad-to...,,,,,,,,
724,Hyderabad to Nandyal,https://www.redbus.in/bus-tickets/hyderabad-to...,,,,,,,,
725,Hyderabad to Nandyal,https://www.redbus.in/bus-tickets/hyderabad-to...,,,,,,,,

**2.Rajasthan**

In [97]:
df_2R=pd.read_csv('Rajasthan.csv')
df_2R

,Route_name,Route_link
0,Udaipur to Jodhpur,https://www.redbus.in/bus-tickets/udaipur-to-j...
1,Jodhpur to Ajmer,https://www.redbus.in/bus-tickets/jodhpur-to-a...
2,Beawar (Rajasthan) to Jaipur (Rajasthan),https://www.redbus.in/bus-tickets/beawer-to-ja...
3,Sikar to Jaipur (Rajasthan),https://www.redbus.in/bus-tickets/sikar-to-jaipur
4,Jaipur (Rajasthan) to Jodhpur,https://www.redbus.in/bus-tickets/jaipur-to-jo...
5,Aligarh (uttar pradesh) to Jaipur (Rajasthan),https://www.redbus.in/bus-tickets/aligarh-utta...
6,Jaipur (Rajasthan) to Aligarh (uttar pradesh),https://www.redbus.in/bus-tickets/jaipur-to-al...
7,Jodhpur to Beawar (Rajasthan),https://www.redbus.in/bus-tickets/jodhpur-to-b...
8,Jaipur (Rajasthan) to Pilani,https://www.redbus.in/bus-tickets/jaipur-to-pi...
9,Kishangarh to Jaipur (Rajasthan),https://www.redbus.in/bus-tickets/kishangarh-t...
10,Udaipur to Jodhpur,https://www.redbus.in/bus-tickets/udaipur-to-j...
11,Jodhpur to Ajmer,https://www.redbus.in/bus-tickets/jodhpur-to-a...
12,Beawar (Rajasthan) to Jaipur (Rajasthan),https://www.redbus.in/bus-tickets/beawer-to-ja...
13,Sikar to Jaipur (Rajasthan),https://www.redbus.in/bus-tickets/sikar-to-jaipur
14,Jaipur (Rajasthan) to Jodhpur,https://www.redbus.in/bus-tickets/jaipur-to-jo...
15,Aligarh (uttar pradesh) to Jaipur (Rajasthan),https://www.redbus.in/bus-tickets/aligarh-utta...
16,Jaipur (Rajasthan) to Aligarh (uttar pradesh),https://www.redbus.in/bus-tickets/jaipur-to-al...
17,Jodhpur to Beawar (Rajasthan),https://www.redbus.in/bus-tickets/jodhpur-to-b...
18,Jaipur (Rajasthan) to Pilani,https://www.redbus.in/bus-tickets/jaipur-to-pi...
19,Kishangarh to Jaipur (Rajasthan),https://www.redbus.in/bus-tickets/kishangarh-t...

In [129]:
# retrive the bus details
driver_R = webdriver.Chrome()
Bus_names_R = []
Bus_types_R = []
Start_Time_R = []
End_Time_R = []
Ratings_R = []
Total_Duration_R = []
Prices_R = []
Seats_Available_R = []
Route_names_R = []
Route_links_R = []

driver_R.maximize_window()
for i,r in df_2R.iterrows():
    link=r["Route_link"]
    routes=r["Route_name"]

# Loop through each link
    driver_R.get(link)
    time.sleep(6) 
    

    # Click on elements to reveal bus details
    elements = driver_R.find_elements(By.XPATH, f"//a[contains(@href, '{link}')]")
    for element in elements:
        element.click()
        time.sleep(2)

    try:
        clicks = driver_R.find_element(By.XPATH, "//div[@class='button']")
        clicks.click()
        
    except:
        continue  
    time.sleep(2)

    number_of_scrolls = 25
    scroll_pause_time = 1  # Adjust this based on the page's loading time

    for _ in range(number_of_scrolls):
        # Scroll down to the bottom using JavaScript
        driver_R.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    
        # Wait for new content to load
        time.sleep(scroll_pause_time)

    # Extract bus details
    bus_name = driver_R.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
    bus_type = driver_R.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
    start_time = driver_R.find_elements(By.XPATH, "//*[@class='dp-time f-19 d-color f-bold']")
    end_time = driver_R.find_elements(By.XPATH, "//*[@class='bp-time f-19 d-color disp-Inline']")
    total_duration = driver_R.find_elements(By.XPATH, "//*[@class='dur l-color lh-24']")
    try:
        rating = driver_R.find_elements(By.XPATH,"//div[@class='clearfix row-one']/div[@class='column-six p-right-10 w-10 fl']")
    except:
        continue
    price = driver_R.find_elements(By.XPATH, '//*[@class="fare d-block"]')
    seats = driver_R.find_elements(By.XPATH, "//div[contains(@class, 'seat-left')]")

    # Append data to respective lists
    for bus in bus_name:
        Bus_names_R.append(bus.text)
        Route_links_R.append(link)
        Route_names_R.append(routes)
    for bus_type_elem in bus_type:
        Bus_types_R.append(bus_type_elem.text)
    for start_time_elem in start_time:
        Start_Time_R.append(start_time_elem.text)
    for end_time_elem in end_time:
        End_Time_R.append(end_time_elem.text)
    for total_duration_elem in total_duration:
        Total_Duration_R.append(total_duration_elem.text)
    for ratings in rating:
        Ratings_R.append(ratings.text)
    for price_elem in price:
        Prices_R.append(price_elem.text)
    for seats_elem in seats:
        Seats_Available_R.append(seats_elem.text)
print("Successfully Completed")

Successfully Completed

In [505]:
# from list to convert data frame
data_R = {
    'Route_name': Route_names_R,
    'Route_link': Route_links_R,
    'Bus_name': Bus_names_R,
    'Bus_type': Bus_types_R,
    'Start_time': Start_Time_R,
    'Total_duration': Total_Duration_R,
    'End_time': End_Time_R,
    "Ratings":Ratings_R,
    'Price': Prices_R,
    "Seats_Available":Seats_Available_R    
}

df_buses_R = pd.DataFrame(data_R)
#convert dataframe to csv

In [509]:
path=r"C:\Users\M Karan kumar\1JupyterNoteBOOk\REDBUS\buses_R.csv"
df_buses_R.to_csv(path,index=False)

In [507]:
df_buses_R

,Route_name,Route_link,Bus_name,Bus_type,Start_time,Total_duration,End_time,Ratings,Price,Seats_Available
0,Udaipur to Jodhpur,https://www.redbus.in/bus-tickets/udaipur-to-j...,RSRTC - 193271,Express Non AC Seater 2+3,19:30,06h 30m,02:00,4.2\n4,INR 294,34 Seats available
1,Udaipur to Jodhpur,https://www.redbus.in/bus-tickets/udaipur-to-j...,RSRTC - 189622,Express Non AC Seater 2+3,22:00,07h 00m,05:00,3.5\n7,INR 294,39 Seats available
2,Udaipur to Jodhpur,https://www.redbus.in/bus-tickets/udaipur-to-j...,Shree Devnarayan Travels,Bharat Benz A/C Seater (2+1),17:00,04h 30m,21:30,4.5\n284,INR 550,10 Seats available
3,Udaipur to Jodhpur,https://www.redbus.in/bus-tickets/udaipur-to-j...,M R Travels,Volvo Multi-Axle I-Shift B11R Semi Sleeper (2+2),17:10,04h 45m,21:55,4.4\n453,INR 485,32 Seats available
4,Udaipur to Jodhpur,https://www.redbus.in/bus-tickets/udaipur-to-j...,Jain travels regd,A/C Seater / Sleeper (2+1),21:30,07h 00m,04:30,4.2\n246,INR 460,26 Seats available
...,...,...,...,...,...,...,...,...,...,...
660,Kishangarh to Jaipur (Rajasthan),https://www.redbus.in/bus-tickets/kishangarh-t...,,,,,,,,
661,Kishangarh to Jaipur (Rajasthan),https://www.redbus.in/bus-tickets/kishangarh-t...,,,,,,,,
662,Kishangarh to Jaipur (Rajasthan),https://www.redbus.in/bus-tickets/kishangarh-t...,,,,,,,,
663,Kishangarh to Jaipur (Rajasthan),https://www.redbus.in/bus-tickets/kishangarh-t...,,,,,,,,
664,Kishangarh to Jaipur (Rajasthan),https://www.redbus.in/bus-tickets/kishangarh-t...,,,,,,,,

**3.Kerala**

In [574]:
df_3K=pd.read_csv('Kerala.csv')

In [576]:
df_3K

,Route_name,Route_link
0,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...
1,Kozhikode to Bangalore,https://www.redbus.in/bus-tickets/kozhikode-to...
2,Kozhikode to Ernakulam,https://www.redbus.in/bus-tickets/kozhikode-to...
3,Ernakulam to Kozhikode,https://www.redbus.in/bus-tickets/ernakulam-to...
4,Bangalore to Kannur,https://www.redbus.in/bus-tickets/bangalore-to...
5,Kozhikode to Mysore,https://www.redbus.in/bus-tickets/kozhikode-to...
6,Kannur to Bangalore,https://www.redbus.in/bus-tickets/kannur-to-ba...
7,Kozhikode to Thiruvananthapuram,https://www.redbus.in/bus-tickets/kozhikode-to...
8,Mysore to Kozhikode,https://www.redbus.in/bus-tickets/mysore-to-ko...
9,Bangalore to Kalpetta (kerala),https://www.redbus.in/bus-tickets/bangalore-to...
10,Kalpetta (kerala) to Bangalore,https://www.redbus.in/bus-tickets/kalpetta-to-...
11,Thiruvananthapuram to Kozhikode,https://www.redbus.in/bus-tickets/thiruvananth...
12,Kozhikode to Thrissur,https://www.redbus.in/bus-tickets/kozhikode-to...
13,Kozhikode to Kottayam,https://www.redbus.in/bus-tickets/kozhikode-to...
14,Kottayam to Kozhikode,https://www.redbus.in/bus-tickets/kottayam-to-...

In [578]:
#retrive the bus details
driver_k = webdriver.Chrome()
Bus_names_k = []
Bus_types_k = []
Start_Time_k = []
End_Time_k = []
Ratings_k = []
Total_Duration_k = []
Prices_k = []
Seats_Available_k = []
Route_names_k= []
Route_links_k = []

driver_k.maximize_window()
for i,r in df_3K.iterrows():
    link=r["Route_link"]
    routes=r["Route_name"]

# Loop through each link
    driver_k.get(link)
    time.sleep(6)  
    

    # Click on elements to reveal bus details
    elements = driver_k.find_elements(By.XPATH, f"//a[contains(@href, '{link}')]")
    for element in elements:
        element.click()
        time.sleep(2)
        
    # click elements to views bus
    try:
        clicks = driver_k.find_element(By.XPATH, "//div[@class='button']")
        clicks.click()
    except:
        continue  
    time.sleep(2)
    
    number_of_scrolls = 25
    scroll_pause_time = 1  # Adjust this based on the page's loading time

    for _ in range(number_of_scrolls):
        # Scroll down to the bottom using JavaScript
        driver_k.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    
        # Wait for new content to load
        time.sleep(scroll_pause_time)

    # Extract bus details
    bus_name = driver_k.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
    bus_type = driver_k.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
    start_time = driver_k.find_elements(By.XPATH, "//*[@class='dp-time f-19 d-color f-bold']")
    end_time = driver_k.find_elements(By.XPATH, "//*[@class='bp-time f-19 d-color disp-Inline']")
    total_duration = driver_k.find_elements(By.XPATH, "//*[@class='dur l-color lh-24']")
    try:
        rating = driver_k.find_elements(By.XPATH,"//div[@class='clearfix row-one']/div[@class='column-six p-right-10 w-10 fl']")
    except:
        continue
    price = driver_k.find_elements(By.XPATH, '//*[@class="fare d-block"]')
    seats = driver_k.find_elements(By.XPATH, "//div[contains(@class, 'seat-left')]")

    # Append data to respective lists
    for bus in bus_name:
        Bus_names_k.append(bus.text)
        Route_links_k.append(link)
        Route_names_k.append(routes)
    for bus_type_elem in bus_type:
        Bus_types_k.append(bus_type_elem.text)
    for start_time_elem in start_time:
        Start_Time_k.append(start_time_elem.text)
    for end_time_elem in end_time:
        End_Time_k.append(end_time_elem.text)
    for total_duration_elem in total_duration:
        Total_Duration_k.append(total_duration_elem.text)
    for ratings in rating:
        Ratings_k.append(ratings.text)
    for price_elem in price:
        Prices_k.append(price_elem.text)
    for seats_elem in seats:
        Seats_Available_k.append(seats_elem.text)
        
print("Successfully Completed")

Successfully Completed

In [582]:
# from list to convert data frame
data_KL = {
    'Route_name': Route_names_k,
    'Route_link': Route_links_k,
    'Bus_name': Bus_names_k,
    'Bus_type': Bus_types_k,
    'Start_time': Start_Time_k,
    'Total_duration': Total_Duration_k,
    'End_time': End_Time_k,
    "Ratings":Ratings_k,
    'Price': Prices_k,
    "Seats_Available":Seats_Available_k 
        
}

df_buses_KL = pd.DataFrame(data_KL)
#convert dataframe to csv
path=r"C:\Users\M Karan kumar\1JupyterNoteBOOk\REDBUS\buses_KL.csv"
df_buses_KL.to_csv(path,index=False)

In [584]:
df_buses_KL

,Route_name,Route_link,Bus_name,Bus_type,Start_time,Total_duration,End_time,Ratings,Price,Seats_Available
0,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...,KSRTC (Kerala) - 52,SWIFT-GARUDA A/C SEATER BUS,12:00,08h 20m,20:20,3.7\n129,INR 627,15 Seats available
1,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...,KSRTC (Kerala) - 129,SWIFT-GARUDA A/C SEATER BUS,14:15,08h 50m,23:05,4.2\n86,INR 627,28 Seats available
2,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...,KSRTC (Kerala) - 235,Swift Deluxe Non AC Air Bus (2+2),15:00,10h 00m,01:00,3.9\n15,INR 620,33 Seats available
3,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...,KSRTC (Kerala) - 370,AC MULTI AXLE,15:25,08h 20m,23:45,2.4\n44,INR 729,23 Seats available
4,Bangalore to Kozhikode,https://www.redbus.in/bus-tickets/bangalore-to...,KSRTC (Kerala) - 97,Swift Deluxe Non AC Air Bus (2+2),16:00,08h 45m,00:45,2.8\n22,INR 567,19 Seats available
...,...,...,...,...,...,...,...,...,...,...
713,Kottayam to Kozhikode,https://www.redbus.in/bus-tickets/kottayam-to-...,Ubc travels,A/C Semi Sleeper (2+2),17:30,07h 30m,01:00,3.7\n3,INR 700,41 Seats available
714,Kottayam to Kozhikode,https://www.redbus.in/bus-tickets/kottayam-to-...,Sonia Travels,A/C Seater/Sleeper (2+1),19:10,07h 19m,02:29,3.0\n1,INR 750,37 Seats available
715,Kottayam to Kozhikode,https://www.redbus.in/bus-tickets/kottayam-to-...,EMERALD TRAVELS,Bharat Benz A/C Seater (2+2),23:00,05h 30m,04:30,2.3\n12,INR 800,36 Seats available
716,Kottayam to Kozhikode,https://www.redbus.in/bus-tickets/kottayam-to-...,Holy Maria Travels,A/C Semi Sleeper (2+2),18:20,07h 50m,02:10,5.0,INR 800,40 Seats available
717,Kottayam to Kozhikode,https://www.redbus.in/bus-tickets/kottayam-to-...,AURA CONNECT,A/C Sleeper (2+1),18:15,08h 05m,02:20,2.4,1899,30 Seats available

**4.Telungana**

In [586]:
df_T=pd.read_csv('Telungana.csv')

In [588]:
df_T

,Route_name,Route_link
0,Hyderabad to Tirupati,https://www.redbus.in/bus-tickets/hyderabad-to...
1,Hyderabad to Godavarikhani,https://www.redbus.in/bus-tickets/hyderabad-to...
2,Hyderabad to Armoor,https://www.redbus.in/bus-tickets/hyderabad-to...
3,Hyderabad to Nandyal,https://www.redbus.in/bus-tickets/hyderabad-to...
4,Hyderabad to Kodad,https://www.redbus.in/bus-tickets/hyderabad-to...
5,Hyderabad to Addanki,https://www.redbus.in/bus-tickets/hyderabad-to...
6,Kothagudem to Hyderabad,https://www.redbus.in/bus-tickets/kothagudem-t...
7,Guntur (Andhra Pradesh) to Hyderabad,https://www.redbus.in/bus-tickets/guntur-to-hy...
8,Hyderabad to Guntur (Andhra Pradesh),https://www.redbus.in/bus-tickets/hyderabad-to...
9,Godavarikhani to Hyderabad,https://www.redbus.in/bus-tickets/godavarikhan...
10,Hyderabad to Kothagudem,https://www.redbus.in/bus-tickets/hyderabad-to...
11,Hyderabad to Sathupally,https://www.redbus.in/bus-tickets/hyderabad-to...
12,Hyderabad to Warangal,https://www.redbus.in/bus-tickets/hyderabad-to...
13,Kodad to Hyderabad,https://www.redbus.in/bus-tickets/kodad-to-hyd...
14,Jagityal to Hyderabad,https://www.redbus.in/bus-tickets/jagityal-to-...
15,Hyderabad to Bhadrachalam,https://www.redbus.in/bus-tickets/hyderabad-to...
16,Hyderabad to Tirupati,https://www.redbus.in/bus-tickets/hyderabad-to...
17,Hyderabad to Godavarikhani,https://www.redbus.in/bus-tickets/hyderabad-to...
18,Hyderabad to Armoor,https://www.redbus.in/bus-tickets/hyderabad-to...
19,Hyderabad to Nandyal,https://www.redbus.in/bus-tickets/hyderabad-to...
20,Hyderabad to Kodad,https://www.redbus.in/bus-tickets/hyderabad-to...
21,Hyderabad to Addanki,https://www.redbus.in/bus-tickets/hyderabad-to...

In [590]:
# retrive the bus details
driver_T = webdriver.Chrome()
Bus_names_T = []
Bus_types_T = []
Start_Time_T = []
End_Time_T = []
Ratings_T = []
Total_Duration_T = []
Prices_T = []
Seats_Available_T = []
Route_names_T = []
Route_links_T = []

driver_T.maximize_window()
for i,r in df_T.iterrows():
    link=r["Route_link"]
    routes=r["Route_name"]

# Loop through each link
    driver_T.get(link)
    time.sleep(6)  
    

    # Click on elements to reveal bus details
    elements = driver_T.find_elements(By.XPATH, f"//a[contains(@href, '{link}')]")
    for element in elements:
        element.click()
        time.sleep(2)

    # click elements to views bus
    try:
        clicks = driver_T.find_element(By.XPATH, "//div[@class='button']")
        clicks.click()
    except:
        continue  
    time.sleep(2)
    
    number_of_scrolls = 25
    scroll_pause_time = 1  # Adjust this based on the page's loading time

    for _ in range(number_of_scrolls):
        # Scroll down to the bottom using JavaScript
        driver_T.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    
        # Wait for new content to load
        time.sleep(scroll_pause_time)
        
    # Extract bus details
    bus_name = driver_T.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
    bus_type = driver_T.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
    start_time = driver_T.find_elements(By.XPATH, "//*[@class='dp-time f-19 d-color f-bold']")
    end_time = driver_T.find_elements(By.XPATH, "//*[@class='bp-time f-19 d-color disp-Inline']")
    total_duration = driver_T.find_elements(By.XPATH, "//*[@class='dur l-color lh-24']")
    try:
        rating = driver_T.find_elements(By.XPATH,"//div[@class='clearfix row-one']/div[@class='column-six p-right-10 w-10 fl']")
    except:
        continue
    price = driver_T.find_elements(By.XPATH, '//*[@class="fare d-block"]')
    seats = driver_T.find_elements(By.XPATH, "//div[contains(@class, 'seat-left')]")

    # Append data to respective lists
    for bus in bus_name:
        Bus_names_T.append(bus.text)
        Route_links_T.append(link)
        Route_names_T.append(routes)
    for bus_type_elem in bus_type:
        Bus_types_T.append(bus_type_elem.text)
    for start_time_elem in start_time:
        Start_Time_T.append(start_time_elem.text)
    for end_time_elem in end_time:
        End_Time_T.append(end_time_elem.text)
    for total_duration_elem in total_duration:
        Total_Duration_T.append(total_duration_elem.text)
    for ratings in rating:
        Ratings_T.append(ratings.text)
    for price_elem in price:
        Prices_T.append(price_elem.text)
    for seats_elem in seats:
        Seats_Available_T.append(seats_elem.text)
print("Successfully Completed")

Successfully Completed

In [592]:
# from list to convert data frame
data_T = {
    'Route_name': Route_names_T,
    'Route_link': Route_links_T,
    'Bus_name': Bus_names_T,
    'Bus_type': Bus_types_T,
    'Start_time': Start_Time_T,
    'Total_duration': Total_Duration_T,
    'End_time': End_Time_T,
    "Ratings":Ratings_T,
    'Price': Prices_T,
    "Seats_Available":Seats_Available_T
    
    
    
}

df_buses_T = pd.DataFrame(data_T)
#convert dataframe to csv
path=r"C:\Users\M Karan kumar\1JupyterNoteBOOk\REDBUS\buses_T.csv"
df_buses_T.to_csv(path,index=False)

In [594]:
df_buses_T

,Route_name,Route_link,Bus_name,Bus_type,Start_time,Total_duration,End_time,Ratings,Price,Seats_Available
0,Hyderabad to Tirupati,https://www.redbus.in/bus-tickets/hyderabad-to...,TGSRTC - 1777,Super Luxury (Non AC Seater 2+2 Push Back),09:30,11h 20m,20:50,2.1\n10,INR 732,1 Seat available
1,Hyderabad to Tirupati,https://www.redbus.in/bus-tickets/hyderabad-to...,TGSRTC - 8265,Super Luxury (Non AC Seater 2+2 Push Back),10:30,10h 45m,21:15,2.5\n28,INR 732,7 Seats available
2,Hyderabad to Tirupati,https://www.redbus.in/bus-tickets/hyderabad-to...,TGSRTC - 6762,Super Luxury (Non AC Seater 2+2 Push Back),11:30,11h 30m,23:00,2.9\n38,INR 732,23 Seats available
3,Hyderabad to Tirupati,https://www.redbus.in/bus-tickets/hyderabad-to...,TGSRTC - 2085,Super Luxury (Non AC Seater 2+2 Push Back),12:50,14h 30m,03:20,3.4\n43,INR 732,10 Seats available
4,Hyderabad to Tirupati,https://www.redbus.in/bus-tickets/hyderabad-to...,TGSRTC - 2429,Super Luxury (Non AC Seater 2+2 Push Back),14:30,13h 00m,03:30,2.1\n3,INR 802,31 Seats available
...,...,...,...,...,...,...,...,...,...,...
265,Hyderabad to Addanki,https://www.redbus.in/bus-tickets/hyderabad-to...,,,,,,,,
266,Hyderabad to Addanki,https://www.redbus.in/bus-tickets/hyderabad-to...,,,,,,,,
267,Hyderabad to Addanki,https://www.redbus.in/bus-tickets/hyderabad-to...,,,,,,,,
268,Hyderabad to Addanki,https://www.redbus.in/bus-tickets/hyderabad-to...,,,,,,,,
269,Hyderabad to Addanki,https://www.redbus.in/bus-tickets/hyderabad-to...,,,,,,,,

**5.Goa**

In [596]:
df_G=pd.read_csv('Goa.csv')

In [598]:
df_G

,Route_name,Route_link
0,Pune to Goa,https://www.redbus.in/bus-tickets/pune-to-goa
1,Goa to Pune,https://www.redbus.in/bus-tickets/goa-to-pune
2,Mumbai to Goa,https://www.redbus.in/bus-tickets/mumbai-to-goa
3,Bangalore to Goa,https://www.redbus.in/bus-tickets/bangalore-to...
4,Goa to Bangalore,https://www.redbus.in/bus-tickets/goa-to-banga...
5,Goa to Mumbai,https://www.redbus.in/bus-tickets/goa-to-mumbai
6,Pandharpur to Goa,https://www.redbus.in/bus-tickets/pandharpur-t...
7,Goa to Pandharpur,https://www.redbus.in/bus-tickets/goa-to-pandh...
8,Solapur to Goa,https://www.redbus.in/bus-tickets/solapur-to-goa
9,Goa to Kolhapur(Maharashtra),https://www.redbus.in/bus-tickets/goa-to-kolha...
10,Goa to Solapur,https://www.redbus.in/bus-tickets/goa-to-solapur
11,Goa to Sangli,https://www.redbus.in/bus-tickets/goa-to-sangli
12,Goa to Sangola (Solapur),https://www.redbus.in/bus-tickets/goa-to-sangola
13,Sangola (Solapur) to Goa,https://www.redbus.in/bus-tickets/sangola-to-goa
14,Goa to Miraj,https://www.redbus.in/bus-tickets/goa-to-miraj
15,Mopa Airport to Goa,https://www.redbus.in/bus-tickets/mopa-airport...
16,Shivamogga to Goa,https://www.redbus.in/bus-tickets/shimoga-to-goa
17,Goa to Satara,https://www.redbus.in/bus-tickets/goa-to-satara

In [608]:
# retrive the bus details
driver_G = webdriver.Chrome()
Bus_names_G = []
Bus_types_G = []
Start_Time_G = []
End_Time_G = []
Ratings_G = []
Total_Duration_G = []
Prices_G = []
Seats_Available_G = []
Route_names_G= []
Route_links_G = []

driver_G.maximize_window()
for i,r in df_G.iterrows():
    link=r["Route_link"]
    routes=r["Route_name"]

# Loop through each link
    driver_G.get(link)
    time.sleep(6)  

    # Click on elements to reveal bus details
    elements = driver_G.find_elements(By.XPATH, f"//a[contains(@href, '{link}')]")
    for element in elements:
        element.click()
        time.sleep(2)
   
    #try:
        #clicks = driver_G.find_element(By.XPATH, "//div[@class='button']")
        #clicks.click()
        
    #except:
        #continue
        #time.sleep(2)

    number_of_scrolls = 25
    scroll_pause_time = 1  # Adjust this based on the page's loading time

    for _ in range(number_of_scrolls):
        # Scroll down to the bottom using JavaScript
        driver_G.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    
        # Wait for new content to load
        time.sleep(scroll_pause_time)

    # Extract bus details
    bus_name = driver_G.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
    bus_type = driver_G.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
    start_time = driver_G.find_elements(By.XPATH, "//*[@class='dp-time f-19 d-color f-bold']")
    end_time = driver_G.find_elements(By.XPATH, "//*[@class='bp-time f-19 d-color disp-Inline']")
    total_duration = driver_G.find_elements(By.XPATH, "//*[@class='dur l-color lh-24']")
    try:
        rating = driver_G.find_elements(By.XPATH,"//div[@class='clearfix row-one']/div[@class='column-six p-right-10 w-10 fl']")
    except:
        continue
    price = driver_G.find_elements(By.XPATH, '//*[@class="fare d-block"]')
    seats = driver_G.find_elements(By.XPATH, "//div[contains(@class, 'seat-left')]")

    # Append data to respective lists
    for bus in bus_name:
        Bus_names_G.append(bus.text)
        Route_links_G.append(link)
        Route_names_G.append(routes)
    for bus_type_elem in bus_type:
        Bus_types_G.append(bus_type_elem.text)
    for start_time_elem in start_time:
        Start_Time_G.append(start_time_elem.text)
    for end_time_elem in end_time:
        End_Time_G.append(end_time_elem.text)
    for total_duration_elem in total_duration:
        Total_Duration_G.append(total_duration_elem.text)
    for ratings in rating:
        Ratings_G.append(ratings.text)
    for price_elem in price:
        Prices_G.append(price_elem.text)
    for seats_elem in seats:
        Seats_Available_G.append(seats_elem.text)
print("Successfully Completed")

Successfully Completed

In [610]:
# from list to convert data frame
data_G = {
    'Route_name': Route_names_G,
    'Route_link': Route_links_G,
    'Bus_name': Bus_names_G,
    'Bus_type': Bus_types_G,
    'Start_time': Start_Time_G,
    'Total_duration': Total_Duration_G,
    'End_time': End_Time_G,
    "Ratings":Ratings_G,
    'Price': Prices_G,
    "Seats_Available":Seats_Available_G   
    
}

df_buses_G = pd.DataFrame(data_G)
#convert dataframe to csv
path=r"C:\Users\M Karan kumar\1JupyterNoteBOOk\REDBUS\buses_G.csv"
df_buses_G.to_csv(path,index=False)

In [612]:
df_buses_G

,Route_name,Route_link,Bus_name,Bus_type,Start_time,Total_duration,End_time,Ratings,Price,Seats_Available
0,Pune to Goa,https://www.redbus.in/bus-tickets/pune-to-goa,Kadamba Transport Corporation Limited (KTCL) -...,A/C Sleeper (2+1),19:15,10h 35m,05:50,3.8\n333,INR 900,9 Seats available
1,Pune to Goa,https://www.redbus.in/bus-tickets/pune-to-goa,Ashray Travels,Non A/C Seater / Sleeper (2+1),21:15,11h 16m,08:31,4.3\n505,INR 500,30 Seats available
2,Pune to Goa,https://www.redbus.in/bus-tickets/pune-to-goa,IntrCity SmartBus,AC Sleeper (2+1),22:00,11h 05m,09:05,4.3\n142,INR 900,32 Seats available
3,Pune to Goa,https://www.redbus.in/bus-tickets/pune-to-goa,AdIntrCity SmartBus,Bharat Benz A/C Sleeper (2+1),22:30,10h 50m,09:20,4.3\n327,INR 900,23 Seats available
4,Pune to Goa,https://www.redbus.in/bus-tickets/pune-to-goa,Dolphin Travel House (37),Bharat Benz A/C Sleeper (2+1),19:45,10h 15m,06:00,4.1\n263,INR 910,32 Seats available
...,...,...,...,...,...,...,...,...,...,...
475,Goa to Satara,https://www.redbus.in/bus-tickets/goa-to-satara,Manish Patil Travels,A/C Sleeper (2+1),15:30,10h 30m,02:00,2.5,INR 1000,30 Seats available
476,Goa to Satara,https://www.redbus.in/bus-tickets/goa-to-satara,VRL Travels,A/C Sleeper (2+1),19:30,08h 30m,04:00,3.4,INR 1000,29 Seats available
477,Goa to Satara,https://www.redbus.in/bus-tickets/goa-to-satara,Anand Tours And Travels,Volvo Multi-Axle I-Shift A/C Sleeper (2+1),20:00,09h 30m,05:30,,INR 2900,41 Seats available
478,Goa to Satara,https://www.redbus.in/bus-tickets/goa-to-satara,Anand Tours And Travels,Volvo Multi-Axle A/C Sleeper (2+1),20:00,09h 00m,05:00,,INR 2900,36 Seats available
479,Goa to Satara,https://www.redbus.in/bus-tickets/goa-to-satara,Anand Tours And Travels,Volvo Multi-Axle A/C Sleeper (2+1),22:45,08h 30m,07:15,,INR 2900,36 Seats available

**6.South Bengal**

In [322]:
df_SB=pd.read_csv('SouthBengal.csv')

In [324]:
df_SB

,Route_name,Route_link
0,Durgapur to Calcutta,https://www.redbus.in/bus-tickets/durgapur-to-...
1,Kolkata to Burdwan,https://www.redbus.in/bus-tickets/kolkata-to-b...
2,Haldia to Calcutta,https://www.redbus.in/bus-tickets/haldia-to-ko...
3,Kolkata to Haldia,https://www.redbus.in/bus-tickets/kolkata-to-h...
4,Kolkata to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/kolkata-to-d...
5,Kolkata to Arambagh (West Bengal),https://www.redbus.in/bus-tickets/kolkata-to-a...
6,Midnapore to Kolkata,https://www.redbus.in/bus-tickets/midnapore-to...
7,Kolkata to Digha,https://www.redbus.in/bus-tickets/kolkata-to-d...
8,Digha to Calcutta,https://www.redbus.in/bus-tickets/digha-to-kol...
9,Kolkata to Bankura,https://www.redbus.in/bus-tickets/kolkata-to-b...
10,Kolkata to Midnapore,https://www.redbus.in/bus-tickets/kolkata-to-m...
11,Kolkata to Asansol (West Bengal),https://www.redbus.in/bus-tickets/kolkata-to-a...
12,Kolkata to Nimtouri,https://www.redbus.in/bus-tickets/kolkata-to-n...
13,Jhargram to Kolkata,https://www.redbus.in/bus-tickets/jhargram-to-...
14,Kolkata to Contai (Kanthi),https://www.redbus.in/bus-tickets/kolkata-to-c...
15,Kolkata to Kolaghat,https://www.redbus.in/bus-tickets/kolkata-to-k...
16,Kolkata to Nandakumar (west bengal),https://www.redbus.in/bus-tickets/kolkata-to-n...
17,Kolkata to Mecheda (West Bengal),https://www.redbus.in/bus-tickets/kolkata-to-m...
18,Digha to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/digha-to-dur...
19,Midnapore to Barasat (West Bengal),https://www.redbus.in/bus-tickets/midnapore-to...
20,Durgapur (West Bengal) to Digha,https://www.redbus.in/bus-tickets/durgapur-to-...
21,Kolkata to Chandipur (West Bengal),https://www.redbus.in/bus-tickets/kolkata-to-c...
22,Barasat (West Bengal) to Midnapore,https://www.redbus.in/bus-tickets/barasat-west...
23,Kolkata to Debra,https://www.redbus.in/bus-tickets/kolkata-to-d...
24,Kirnahar (West Bengal) to Kolkata,https://www.redbus.in/bus-tickets/kirnahar-wes...
25,Kolkata to Panskura,https://www.redbus.in/bus-tickets/kolkata-to-p...
26,Kolkata to Heria,https://www.redbus.in/bus-tickets/kolkata-to-h...
27,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...
28,Illambazar to Kolkata,https://www.redbus.in/bus-tickets/illambazar-t...
29,Kolkata to Suri,https://www.redbus.in/bus-tickets/kolkata-to-suri
30,Berhampore (West Bengal) to Durgapur (West Ben...,https://www.redbus.in/bus-tickets/berhampore-t...
31,Purulia to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/purulia-to-d...
32,Durgapur (West Bengal) to Berhampore (West Ben...,https://www.redbus.in/bus-tickets/durgapur-to-...
33,Kolkata to Futishanko,https://www.redbus.in/bus-tickets/kolkata-to-f...
34,Kolkata to Kirnahar (West Bengal),https://www.redbus.in/bus-tickets/kolkata-to-k...
35,Durgapur (West Bengal) to Barasat (West Bengal),https://www.redbus.in/bus-tickets/durgapur-to-...
36,Kolkata to Ramnagar (West Bengal),https://www.redbus.in/bus-tickets/kolkata-to-r...
37,Durgapur (West Bengal) to Purulia,https://www.redbus.in/bus-tickets/durgapur-to-...
38,Durgapur (West Bengal) to Bankura,https://www.redbus.in/bus-tickets/durgapur-to-...
39,Kolkata to Ashari,https://www.redbus.in/bus-tickets/kolkata-to-a...
40,Barasat (West Bengal) to Digha,https://www.redbus.in/bus-tickets/barasat-west...

In [531]:
# retrive the bus details
driver_SB = webdriver.Chrome()
Bus_names_SB = []
Bus_types_SB = []
Start_Time_SB = []
End_Time_SB = []
Ratings_SB = []
Total_Duration_SB = []
Prices_SB = []
Seats_Available_SB = []
Route_names_SB = []
Route_links_SB = []

driver_SB.maximize_window()
for i,r in df_SB.iterrows():
    link=r["Route_link"]
    routes=r["Route_name"]

# Loop through each link
    driver_SB.get(link)
    time.sleep(6)  

    # Click on elements to reveal bus details
    elements = driver_SB.find_elements(By.XPATH, f"//a[contains(@href, '{link}')]")
    for element in elements:
        element.click()
        time.sleep(2)
    #try:
        #clicks = driver_SB.find_element(By.XPATH, "//div[@class='button']")
        #clicks.click()
    #except:
        #continue
        #time.sleep(2)
    
    number_of_scrolls = 25
    scroll_pause_time = 1  # Adjust this based on the page's loading time

    for _ in range(number_of_scrolls):
        # Scroll down to the bottom using JavaScript
        driver_SB.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    
        # Wait for new content to load
        time.sleep(scroll_pause_time)

    # Extract bus details
    bus_name = driver_SB.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
    bus_type = driver_SB.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
    start_time = driver_SB.find_elements(By.XPATH, "//*[@class='dp-time f-19 d-color f-bold']")
    end_time = driver_SB.find_elements(By.XPATH, "//*[@class='bp-time f-19 d-color disp-Inline']")
    total_duration = driver_SB.find_elements(By.XPATH, "//*[@class='dur l-color lh-24']")
    try:
        rating = driver_SB.find_elements(By.XPATH,"//div[@class='clearfix row-one']/div[@class='column-six p-right-10 w-10 fl']")
    except:
        continue
    price = driver_SB.find_elements(By.XPATH, '//*[@class="fare d-block"]')
    seats = driver_SB.find_elements(By.XPATH, "//div[contains(@class, 'seat-left')]")

    # Append data to respective lists
    for bus in bus_name:
        Bus_names_SB.append(bus.text)
        Route_links_SB.append(link)
        Route_names_SB.append(routes)
    for bus_type_elem in bus_type:
        Bus_types_SB.append(bus_type_elem.text)
    for start_time_elem in start_time:
        Start_Time_SB.append(start_time_elem.text)
    for end_time_elem in end_time:
        End_Time_SB.append(end_time_elem.text)
    for total_duration_elem in total_duration:
        Total_Duration_SB.append(total_duration_elem.text)
    for ratings in rating:
        Ratings_SB.append(ratings.text)
    for price_elem in price:
        Prices_SB.append(price_elem.text)
    for seats_elem in seats:
        Seats_Available_SB.append(seats_elem.text)
print("Successfully Completed")

Successfully Completed

In [533]:
# from list to convert data frame
data_SB = {
    'Route_name': Route_names_SB,
    'Route_link': Route_links_SB,
    'Bus_name': Bus_names_SB,
    'Bus_type': Bus_types_SB,
    'Start_time': Start_Time_SB,
    'Total_duration': Total_Duration_SB,
    'End_time': End_Time_SB,
    "Ratings":Ratings_SB,
    'Price': Prices_SB,
    "Seats_Available":Seats_Available_SB 
    
}

df_buses_SB = pd.DataFrame(data_SB)
#convert dataframe to csv
path=r"C:\Users\M Karan kumar\1JupyterNoteBOOk\REDBUS\buses_SB.csv"
df_buses_SB.to_csv(path,index=False)

In [535]:
df_buses_SB

,Route_name,Route_link,Bus_name,Bus_type,Start_time,Total_duration,End_time,Ratings,Price,Seats_Available
0,Durgapur to Calcutta,https://www.redbus.in/bus-tickets/durgapur-to-...,Royal Cruiser,Scania Multi-Axle AC Semi Sleeper (2+2),02:00,04h 00m,06:00,4.2\n86,463,14 Seats available
1,Durgapur to Calcutta,https://www.redbus.in/bus-tickets/durgapur-to-...,SHYAMOLI Pvt. Ltd.(Karunamoyee),Volvo A/C Seater (2+2),06:10,03h 10m,09:20,4.2\n167,INR 486,23 Seats available
2,Durgapur to Calcutta,https://www.redbus.in/bus-tickets/durgapur-to-...,Express Line (Karunamoyee),Volvo 9600 Multi Axle Semi-Sleeper (2+2),06:10,03h 10m,09:20,4.6\n218,INR 486,20 Seats available
3,Durgapur to Calcutta,https://www.redbus.in/bus-tickets/durgapur-to-...,Greenline,Volvo A/C Seater (2+2),06:30,03h 15m,09:45,4.3\n227,INR 486,20 Seats available
4,Durgapur to Calcutta,https://www.redbus.in/bus-tickets/durgapur-to-...,SHYAMOLI Pvt. Ltd.(Karunamoyee),Volvo A/C Seater (2+2),06:40,03h 20m,10:00,4.2\n322,INR 486,31 Seats available
...,...,...,...,...,...,...,...,...,...,...
556,Kolkata to Ashari,https://www.redbus.in/bus-tickets/kolkata-to-a...,SBSTC-ASANSOL - BELDA - VIA - KOLKATA - 08:50 ...,Non AC Seater (2+3),16:00,08h 00m,00:00,3.9,INR 82,52 Seats available
557,Kolkata to Ashari,https://www.redbus.in/bus-tickets/kolkata-to-a...,SBSTC-KOLKATA - ROHINI - VIA - KULTIKRI - 16:2...,Non AC Seater (2+3),16:20,07h 40m,00:00,3.9,INR 82,52 Seats available
558,Kolkata to Ashari,https://www.redbus.in/bus-tickets/kolkata-to-a...,SBSTC-KOLKATA - JHARGRAM - VIA - LODHASULI - 1...,Non AC Seater (2+3),16:50,07h 10m,00:00,3.5\n16,INR 82,52 Seats available
559,Kolkata to Ashari,https://www.redbus.in/bus-tickets/kolkata-to-a...,SBSTC-KOLKATA - MIDNAPUR - 18:00 (MID DEPOT) -...,Non AC Seater (2+3),18:00,06h 00m,00:00,4.0\n15,INR 82,52 Seats available
560,Kolkata to Ashari,https://www.redbus.in/bus-tickets/kolkata-to-a...,SBSTC-KOLKATA - MIDNAPUR - 18:45 (MID DEPOT) -...,Non AC Seater (2+3),18:45,05h 15m,00:00,3.6\n15,INR 82,51 Seats available

**7.Haryana**

In [348]:
df_H=pd.read_csv('Haryana.csv')

In [350]:
df_H

,Route_name,Route_link
0,Delhi to Shimla,https://www.redbus.in/bus-tickets/delhi-to-shimla
1,Chandigarh to Hamirpur (Himachal Pradesh),https://www.redbus.in/bus-tickets/chandigarh-t...
2,Hamirpur (Himachal Pradesh) to Chandigarh,https://www.redbus.in/bus-tickets/hamirpur-him...
3,Shimla to Delhi,https://www.redbus.in/bus-tickets/shimla-to-delhi
4,Delhi to Chandigarh,https://www.redbus.in/bus-tickets/delhi-to-cha...
5,Hamirpur (Himachal Pradesh) to Delhi,https://www.redbus.in/bus-tickets/hamirpur-him...
6,Chamba (Himachal Pradesh) to Chandigarh,https://www.redbus.in/bus-tickets/chamba-himac...
7,Delhi to Hamirpur (Himachal Pradesh),https://www.redbus.in/bus-tickets/delhi-to-ham...
8,Chandigarh to Dharamshala (Himachal Pradesh),https://www.redbus.in/bus-tickets/chandigarh-t...
9,Delhi to Chamba (Himachal Pradesh),https://www.redbus.in/bus-tickets/delhi-to-cha...
10,Chamba (Himachal Pradesh) to Delhi,https://www.redbus.in/bus-tickets/chamba-himac...
11,Kangra to Chandigarh,https://www.redbus.in/bus-tickets/kangra-to-ch...
12,Shimla to Chandigarh,https://www.redbus.in/bus-tickets/shimla-to-ch...
13,Delhi to Baddi (Himachal Pradesh),https://www.redbus.in/bus-tickets/delhi-to-bad...
14,Delhi to Solan,https://www.redbus.in/bus-tickets/delhi-to-solan
15,Delhi to Nalagarh,https://www.redbus.in/bus-tickets/delhi-to-nal...
16,Dharamshala (Himachal Pradesh) to Chandigarh,https://www.redbus.in/bus-tickets/dharamshala-...
17,Palampur to Chandigarh,https://www.redbus.in/bus-tickets/palampur-to-...
18,Ghumarwin to Delhi,https://www.redbus.in/bus-tickets/ghumarwin-to...
19,Chandigarh to Kangra,https://www.redbus.in/bus-tickets/chandigarh-t...
20,Baddi (Himachal Pradesh) to Delhi,https://www.redbus.in/bus-tickets/baddi-himach...
21,Manali to Chandigarh,https://www.redbus.in/bus-tickets/manali-to-ch...
22,Solan to Delhi,https://www.redbus.in/bus-tickets/solan-to-delhi
23,Chandigarh to Manali,https://www.redbus.in/bus-tickets/chandigarh-t...
24,Delhi to Sarkaghat,https://www.redbus.in/bus-tickets/delhi-to-sar...
25,Ghumarwin to Chandigarh,https://www.redbus.in/bus-tickets/ghumarwin-to...
26,Chandigarh to Kullu,https://www.redbus.in/bus-tickets/chandigarh-t...
27,Delhi to Bilaspur (Himachal Pradesh),https://www.redbus.in/bus-tickets/delhi-to-bil...
28,Delhi to Ghumarwin,https://www.redbus.in/bus-tickets/delhi-to-ghu...
29,Chamba (Himachal Pradesh) to Shimla,https://www.redbus.in/bus-tickets/chamba-himac...
30,Delhi to Palampur,https://www.redbus.in/bus-tickets/delhi-to-pal...
31,Chandigarh to Reckong Peo (Himachal Pradesh),https://www.redbus.in/bus-tickets/chandigarh-t...
32,Bilaspur (Himachal Pradesh) to Delhi,https://www.redbus.in/bus-tickets/bilaspur-him...
33,Sarkaghat to Delhi,https://www.redbus.in/bus-tickets/sarkaghat-to...
34,Manali to Delhi,https://www.redbus.in/bus-tickets/manali-to-delhi

In [364]:
# retrive the bus details
driver_H = webdriver.Chrome()
Bus_names_H = []
Bus_types_H = []
Start_Time_H = []
End_Time_H = []
Ratings_H = []
Total_Duration_H = []
Prices_H = []
Seats_Available_H = []
Route_names_H = []
Route_links_H = []

driver_H.maximize_window()
for i,r in df_H.iterrows():
    link=r["Route_link"]
    routes=r["Route_name"]

# Loop through each link
    driver_H.get(link)
    time.sleep(6)  

    # Click on elements to reveal bus details
    elements = driver_H.find_elements(By.XPATH, f"//a[contains(@href, '{link}')]")
    for element in elements:
        element.click()
        time.sleep(2)

    try:
        clicks = driver_H.find_element(By.XPATH, "//div[@class='button']")
        clicks.click()
    except:
        continue
        time.sleep(2)
         
    number_of_scrolls = 25
    scroll_pause_time = 1  # Adjust this based on the page's loading time

    for _ in range(number_of_scrolls):
        # Scroll down to the bottom using JavaScript
        driver_H.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    
        # Wait for new content to load
        time.sleep(scroll_pause_time)

    # Extract bus details
    bus_name = driver_H.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
    bus_type = driver_H.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
    start_time = driver_H.find_elements(By.XPATH, "//*[@class='dp-time f-19 d-color f-bold']")
    end_time = driver_H.find_elements(By.XPATH, "//*[@class='bp-time f-19 d-color disp-Inline']")
    total_duration = driver_H.find_elements(By.XPATH, "//*[@class='dur l-color lh-24']")
    try:
        rating = driver_H.find_elements(By.XPATH,"//div[@class='clearfix row-one']/div[@class='column-six p-right-10 w-10 fl']")
    except:
        continue
    price = driver_H.find_elements(By.XPATH, '//*[@class="fare d-block"]')
    seats = driver_H.find_elements(By.XPATH, "//div[contains(@class, 'seat-left')]")

    # Append data to respective lists
    for bus in bus_name:
        Bus_names_H.append(bus.text)
        Route_links_H.append(link)
        Route_names_H.append(routes)
    for bus_type_elem in bus_type:
        Bus_types_H.append(bus_type_elem.text)
    for start_time_elem in start_time:
        Start_Time_H.append(start_time_elem.text)
    for end_time_elem in end_time:
        End_Time_H.append(end_time_elem.text)
    for total_duration_elem in total_duration:
        Total_Duration_H.append(total_duration_elem.text)
    for ratings in rating:
        Ratings_H.append(ratings.text)
    for price_elem in price:
        Prices_H.append(price_elem.text)
    for seats_elem in seats:
        Seats_Available_H.append(seats_elem.text)
print("Successfully Completed")

Successfully Completed

In [515]:
# from list to convert data frame
data_H = {
    'Route_name': Route_names_H,
    'Route_link': Route_links_H,
    'Bus_name': Bus_names_H,
    'Bus_type': Bus_types_H,
    'Start_time': Start_Time_H,
    'Total_duration': Total_Duration_H,
    'End_time': End_Time_H,
    "Ratings":Ratings_H,
    'Price': Prices_H,
    "Seats_Available":Seats_Available_H   
}

df_buses_H = pd.DataFrame(data_H)
#convert dataframe to csv
path=r"C:\Users\M Karan kumar\1JupyterNoteBOOk\REDBUS\buses_H.csv"
df_buses_H.to_csv(path,index=False)

In [517]:
df_buses_H

,Route_name,Route_link,Bus_name,Bus_type,Start_time,Total_duration,End_time,Ratings,Price,Seats_Available
0,Delhi to Shimla,https://www.redbus.in/bus-tickets/delhi-to-shimla,RSRTC - 192344,Super Luxury Volvo AC Seater Pushback 2+2,03:00,11h 00m,14:00,2.3\n2,INR 1117,35 Seats available
1,Delhi to Shimla,https://www.redbus.in/bus-tickets/delhi-to-shimla,Bedi Travels,Volvo A/C Semi Sleeper (2+2),23:00,09h 00m,08:00,4.8\n890,477,33 Seats available
2,Delhi to Shimla,https://www.redbus.in/bus-tickets/delhi-to-shimla,Laxmi holidays,Scania Multi-Axle AC Semi Sleeper (2+2),23:30,08h 30m,08:00,4.6\n798,569,47 Seats available
3,Delhi to Shimla,https://www.redbus.in/bus-tickets/delhi-to-shimla,Laxmi holidays,Volvo A/C Semi Sleeper (2+2),23:25,08h 20m,07:45,4.5\n658,569,34 Seats available
4,Delhi to Shimla,https://www.redbus.in/bus-tickets/delhi-to-shimla,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...
467,Manali to Delhi,https://www.redbus.in/bus-tickets/manali-to-delhi,,,,,,,,
468,Manali to Delhi,https://www.redbus.in/bus-tickets/manali-to-delhi,,,,,,,,
469,Manali to Delhi,https://www.redbus.in/bus-tickets/manali-to-delhi,,,,,,,,
470,Manali to Delhi,https://www.redbus.in/bus-tickets/manali-to-delhi,,,,,,,,
471,Manali to Delhi,https://www.redbus.in/bus-tickets/manali-to-delhi,,,,,,,,

**8.Assam**

In [370]:
df_AS=pd.read_csv('Assam.csv')

In [372]:
df_AS

,Route_name,Route_link
0,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...
1,Guwahati to Tezpur,https://www.redbus.in/bus-tickets/guwahati-to-...
2,Guwahati to Nagaon (Assam),https://www.redbus.in/bus-tickets/guwahati-to-...
3,Nagaon (Assam) to Guwahati,https://www.redbus.in/bus-tickets/nagaon-to-gu...
4,Goalpara to Guwahati,https://www.redbus.in/bus-tickets/goalpara-to-...
5,Jorhat to North Lakhimpur,https://www.redbus.in/bus-tickets/jorhat-to-no...
6,Dhubri to Guwahati,https://www.redbus.in/bus-tickets/dhubri-to-gu...
7,Jorhat to Dibrugarh,https://www.redbus.in/bus-tickets/jorhat-to-di...
8,North Lakhimpur to Jorhat,https://www.redbus.in/bus-tickets/north-lakhim...
9,North Lakhimpur to Sibsagar,https://www.redbus.in/bus-tickets/north-lakhim...
10,Guwahati to Dhubri,https://www.redbus.in/bus-tickets/guwahati-to-...
11,Dhekiajuli to Guwahati,https://www.redbus.in/bus-tickets/dhekiajuli-t...
12,Sibsagar to North Lakhimpur,https://www.redbus.in/bus-tickets/sibsagar-to-...
13,Dibrugarh to Jorhat,https://www.redbus.in/bus-tickets/dibrugarh-to...
14,Jorhat to Dhemaji,https://www.redbus.in/bus-tickets/jorhat-to-dh...
15,Jorhat to Tinsukia,https://www.redbus.in/bus-tickets/jorhat-to-ti...
16,Tezpur to Dibrugarh,https://www.redbus.in/bus-tickets/tezpur-to-di...
17,Dhemaji to Jorhat,https://www.redbus.in/bus-tickets/dhemaji-to-j...
18,North Lakhimpur to Tezpur,https://www.redbus.in/bus-tickets/north-lakhim...
19,Guwahati to Biswanath Charali,https://www.redbus.in/bus-tickets/guwahati-to-...
20,North Lakhimpur to Dibrugarh,https://www.redbus.in/bus-tickets/north-lakhim...
21,Tinsukia to Jorhat,https://www.redbus.in/bus-tickets/tinsukia-to-...
22,Tezpur to North Lakhimpur,https://www.redbus.in/bus-tickets/tezpur-to-no...
23,North Lakhimpur to Moran,https://www.redbus.in/bus-tickets/north-lakhim...
24,Guwahati to Gohpur,https://www.redbus.in/bus-tickets/guwahati-to-...
25,Guwahati to Kaliabor,https://www.redbus.in/bus-tickets/guwahati-to-...
26,Guwahati to Tumuki (Tezpur Medical),https://www.redbus.in/bus-tickets/guwahati-to-...
27,Dibrugarh to Tezpur,https://www.redbus.in/bus-tickets/dibrugarh-to...
28,Biswanath Charali to Guwahati,https://www.redbus.in/bus-tickets/biswanath-ch...
29,Dibrugarh to North Lakhimpur,https://www.redbus.in/bus-tickets/dibrugarh-to...
30,Moran to North Lakhimpur,https://www.redbus.in/bus-tickets/moran-to-nor...
31,Tumuki (Tezpur Medical) to Guwahati,https://www.redbus.in/bus-tickets/tumuki-tezpu...
32,Biswanath Charali to Dibrugarh,https://www.redbus.in/bus-tickets/biswanath-ch...
33,Gohpur to Guwahati,https://www.redbus.in/bus-tickets/gohpur-to-gu...
34,Sibsagar to Dhemaji,https://www.redbus.in/bus-tickets/sibsagar-to-...
35,North Lakhimpur to Guwahati,https://www.redbus.in/bus-tickets/north-lakhim...
36,Haflong to Guwahati,https://www.redbus.in/bus-tickets/haflong-to-g...
37,Tezpur to Moran,https://www.redbus.in/bus-tickets/tezpur-to-moran
38,Moran to Tezpur,https://www.redbus.in/bus-tickets/moran-to-tezpur
39,Bokakhat to Dibrugarh,https://www.redbus.in/bus-tickets/bokakhat-to-...

In [382]:
# retrive the bus details
driver_AS = webdriver.Chrome()
Bus_names_AS = []
Bus_types_AS = []
Start_Time_AS = []
End_Time_AS = []
Ratings_AS = []
Total_Duration_AS = []
Prices_AS = []
Seats_Available_AS = []
Route_names_AS = []
Route_links_AS = []

driver_AS.maximize_window()
for i,r in df_AS.iterrows():
    link=r["Route_link"]
    routes=r["Route_name"]
# Loop through each link
    driver_AS.get(link)
    time.sleep(6)  

    # Click on elements to reveal bus details
    elements = driver_AS.find_elements(By.XPATH, f"//a[contains(@href, '{link}')]")
    for element in elements:
        element.click()
        time.sleep(2)

    try:
        clicks = driver_AS.find_element(By.XPATH, "//div[@class='button']")
        clicks.click()
    except:
        continue
        time.sleep(2)
         
    number_of_scrolls = 25
    scroll_pause_time = 1  # Adjust this based on the page's loading time

    for _ in range(number_of_scrolls):
        # Scroll down to the bottom using JavaScript
        driver_AS.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    
        # Wait for new content to load
        time.sleep(scroll_pause_time)

    # Extract bus details
    bus_name = driver_AS.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
    bus_type = driver_AS.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
    start_time = driver_AS.find_elements(By.XPATH, "//*[@class='dp-time f-19 d-color f-bold']")
    end_time = driver_AS.find_elements(By.XPATH, "//*[@class='bp-time f-19 d-color disp-Inline']")
    total_duration = driver_AS.find_elements(By.XPATH, "//*[@class='dur l-color lh-24']")
    try:
        rating = driver_AS.find_elements(By.XPATH,"//div[@class='clearfix row-one']/div[@class='column-six p-right-10 w-10 fl']")
    except:
        continue
    price = driver_AS.find_elements(By.XPATH, '//*[@class="fare d-block"]')
    seats = driver_AS.find_elements(By.XPATH, "//div[contains(@class, 'seat-left')]")

    # Append data to respective lists
    for bus in bus_name:
        Bus_names_AS.append(bus.text)
        Route_links_AS.append(link)
        Route_names_AS.append(routes)
    for bus_type_elem in bus_type:
        Bus_types_AS.append(bus_type_elem.text)
    for start_time_elem in start_time:
        Start_Time_AS.append(start_time_elem.text)
    for end_time_elem in end_time:
        End_Time_AS.append(end_time_elem.text)
    for total_duration_elem in total_duration:
        Total_Duration_AS.append(total_duration_elem.text)
    for ratings in rating:
        Ratings_AS.append(ratings.text)
    for price_elem in price:
        Prices_AS.append(price_elem.text)
    for seats_elem in seats:
        Seats_Available_AS.append(seats_elem.text)
print("Successfully Completed")

Successfully Completed

In [519]:
# from list to convert data frame
data_AS = {
    'Route_name': Route_names_AS,
    'Route_link': Route_links_AS,
    'Bus_name': Bus_names_AS,
    'Bus_type': Bus_types_AS,
    'Start_time': Start_Time_AS,
    'Total_duration': Total_Duration_AS,
    'End_time': End_Time_AS,
    "Ratings":Ratings_AS,
    'Price': Prices_AS,
    "Seats_Available":Seats_Available_AS
    
}

df_buses_AS = pd.DataFrame(data_AS)
#convert dataframe to csv
path=r"C:\Users\M Karan kumar\1JupyterNoteBOOk\REDBUS\buses_AS.csv"
df_buses_AS.to_csv(path,index=False)

In [392]:
df_buses_AS

,Route_name,Route_link,Bus_name,Bus_type,Start_time,Total_duration,End_time,Ratings,Price,Seats_Available
0,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Assam State Transport Corporation (ASTC) - 147480,Bharat Benz A/C Seater (2+2),05:00,04h 00m,09:00,3.8\n339,INR 270,4 Seats available
1,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Assam State Transport Corporation (ASTC) - 167476,Bharat Benz A/C Seater (2+2),07:35,04h 10m,11:45,5.0\n2,INR 298,16 Seats available
2,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Assam State Transport Corporation (ASTC) - 157959,Bharat Benz A/C Seater (2+2),14:00,04h 30m,18:30,4.2\n241,INR 298,18 Seats available
3,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Assam State Transport Corporation (ASTC) - 154930,Volvo AC Seater 2+2,15:45,04h 15m,20:00,3.9\n73,INR 298,28 Seats available
4,Tezpur to Guwahati,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Assam State Transport Corporation (ASTC) - 161055,Volvo AC Seater 2+2,16:15,04h 15m,20:30,4.3\n124,INR 298,21 Seats available
...,...,...,...,...,...,...,...,...,...,...
189,Dibrugarh to North Lakhimpur,https://www.redbus.in/bus-tickets/dibrugarh-to...,BARBIE TRAVELS,NON A/C Hi-Tech Push Back (2+2),15:30,04h 00m,19:30,4.0\n1,INR 240,40 Seats available
190,Dibrugarh to North Lakhimpur,https://www.redbus.in/bus-tickets/dibrugarh-to...,Maa Jagadamba,A/C Seater Push Back (2+2),16:15,03h 15m,19:30,4.1\n15,INR 240,41 Seats available
191,Dibrugarh to North Lakhimpur,https://www.redbus.in/bus-tickets/dibrugarh-to...,Maa Jagadamba,A/C Seater Push Back (2+2),16:20,03h 10m,19:30,3.9,INR 240,41 Seats available
192,Dibrugarh to North Lakhimpur,https://www.redbus.in/bus-tickets/dibrugarh-to...,Air Bus Travels,NON AC Seater / Sleeper 2+1,19:40,05h 20m,01:00,3.6\n8,INR 400,46 Seats available
193,Dibrugarh to North Lakhimpur,https://www.redbus.in/bus-tickets/dibrugarh-to...,Air Bus Travels,NON AC Seater / Sleeper 2+1,21:15,04h 45m,02:00,3.7\n4,INR 400,46 Seats available

**9.UttraPradhesh**

In [614]:
df_UP=pd.read_csv('UttraPradhesh.csv')

In [616]:
df_UP

,Route_name,Route_link
0,Delhi to Bareilly,https://www.redbus.in/bus-tickets/delhi-to-bar...
1,Bareilly to Delhi,https://www.redbus.in/bus-tickets/bareilly-to-...
2,Aligarh (uttar pradesh) to Delhi,https://www.redbus.in/bus-tickets/aligarh-utta...
3,Delhi to Aligarh (uttar pradesh),https://www.redbus.in/bus-tickets/delhi-to-ali...
4,Lucknow to Allahabad,https://www.redbus.in/bus-tickets/lucknow-to-a...
5,Lucknow to Delhi,https://www.redbus.in/bus-tickets/lucknow-to-d...
6,Delhi to Farrukhabad (Uttar Pradesh),https://www.redbus.in/bus-tickets/delhi-to-far...
7,Farrukhabad (Uttar Pradesh) to Delhi,https://www.redbus.in/bus-tickets/farrukhabad-...
8,Badaun to Delhi,https://www.redbus.in/bus-tickets/badaun-to-delhi
9,Allahabad to Lucknow,https://www.redbus.in/bus-tickets/allahabad-to...
10,Lucknow to Agra,https://www.redbus.in/bus-tickets/lucknow-to-agra
11,Sitapur (Uttar Pradesh) to Delhi,https://www.redbus.in/bus-tickets/sitapur-to-d...
12,Delhi to Badaun,https://www.redbus.in/bus-tickets/delhi-to-badaun
13,Delhi to Sitapur (Uttar Pradesh),https://www.redbus.in/bus-tickets/delhi-to-sit...
14,Agra to Delhi,https://www.redbus.in/bus-tickets/agra-to-delhi
15,Delhi to Moradabad,https://www.redbus.in/bus-tickets/delhi-to-mor...
16,Delhi to Lucknow,https://www.redbus.in/bus-tickets/delhi-to-luc...
17,Agra to Lucknow,https://www.redbus.in/bus-tickets/agra-to-lucknow
18,Lucknow to Varanasi,https://www.redbus.in/bus-tickets/lucknow-to-v...
19,Agra to Bareilly,https://www.redbus.in/bus-tickets/agra-to-bare...
20,Lucknow to Bareilly,https://www.redbus.in/bus-tickets/lucknow-to-b...
21,Bareilly to Agra,https://www.redbus.in/bus-tickets/bareilly-to-...
22,Delhi to Agra,https://www.redbus.in/bus-tickets/delhi-to-agra
23,Varanasi to Lucknow,https://www.redbus.in/bus-tickets/varanasi-to-...
24,Moradabad to Delhi,https://www.redbus.in/bus-tickets/moradabad-to...
25,Kanpur (Uttar Pradesh) to Jhansi,https://www.redbus.in/bus-tickets/kanpur-to-jh...
26,Delhi to Shahjahanpur (Uttar Pradesh),https://www.redbus.in/bus-tickets/delhi-to-sha...
27,Shahjahanpur (Uttar Pradesh) to Delhi,https://www.redbus.in/bus-tickets/shahjahanpur...
28,Gorakhpur (uttar pradesh) to Lucknow,https://www.redbus.in/bus-tickets/gorakhpur-to...
29,Kanpur (Uttar Pradesh) to Bareilly,https://www.redbus.in/bus-tickets/kanpur-to-ba...
30,Lucknow to Aligarh (uttar pradesh),https://www.redbus.in/bus-tickets/lucknow-to-a...
31,Lucknow to Kanpur (Uttar Pradesh),https://www.redbus.in/bus-tickets/lucknow-to-k...
32,Delhi to Pilibhit,https://www.redbus.in/bus-tickets/delhi-to-pil...
33,Lucknow to Ballia,https://www.redbus.in/bus-tickets/lucknow-to-b...
34,Delhi to Etah (Uttar Pradesh),https://www.redbus.in/bus-tickets/delhi-to-eta...
35,Lucknow to Gorakhpur (uttar pradesh),https://www.redbus.in/bus-tickets/lucknow-to-g...
36,Aligarh (uttar pradesh) to Lucknow,https://www.redbus.in/bus-tickets/aligarh-to-l...
37,Aligarh (uttar pradesh) to Agra,https://www.redbus.in/bus-tickets/aligarh-to-agra
38,Bareilly to Dehradun,https://www.redbus.in/bus-tickets/bareilly-to-...
39,Pilibhit to Delhi,https://www.redbus.in/bus-tickets/pilibhit-to-...
40,Bareilly to Lucknow,https://www.redbus.in/bus-tickets/bareilly-to-...
41,Delhi to Dehradun,https://www.redbus.in/bus-tickets/delhi-to-deh...
42,Varanasi to Allahabad,https://www.redbus.in/bus-tickets/varanasi-to-...
43,Lucknow to Mathura,https://www.redbus.in/bus-tickets/lucknow-to-m...
44,Jhansi to Kanpur (Uttar Pradesh),https://www.redbus.in/bus-tickets/jhansi-to-ka...
45,Dehradun to Bareilly,https://www.redbus.in/bus-tickets/dehradun-to-...
46,Kanpur (Uttar Pradesh) to Lucknow,https://www.redbus.in/bus-tickets/kanpur-to-lu...
47,Aligarh (uttar pradesh) to Greater noida (utta...,https://www.redbus.in/bus-tickets/aligarh-to-g...
48,Etah (Uttar Pradesh) to Delhi,https://www.redbus.in/bus-tickets/etah-up-to-d...

In [618]:
# retrive the bus details
driver_UP = webdriver.Chrome()
Bus_names_UP = []
Bus_types_UP = []
Start_Time_UP = []
End_Time_UP = []
Ratings_UP = []
Total_Duration_UP = []
Prices_UP = []
Seats_Available_UP = []
Route_names_UP = []
Route_links_UP = []

driver_UP.maximize_window()
for i,r in df_UP.iterrows():
    link=r["Route_link"]
    routes=r["Route_name"]

# Loop through each link
    driver_UP.get(link)
    time.sleep(6)  

    # Click on elements to reveal bus details
    elements = driver_UP.find_elements(By.XPATH, f"//a[contains(@href, '{link}')]")
    for element in elements:
        element.click()
        time.sleep(2) 

    try:
        clicks = driver_UP.find_element(By.XPATH, "//div[@class='button']")
        clicks.click()
    except:
        continue
        time.sleep(2)
         
        
    number_of_scrolls = 25
    scroll_pause_time = 1  # Adjust this based on the page's loading time

    for _ in range(number_of_scrolls):
        # Scroll down to the bottom using JavaScript
        driver_UP.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    
        # Wait for new content to load
        time.sleep(scroll_pause_time)

    # Extract bus details
    bus_name = driver_UP.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
    bus_type = driver_UP.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
    start_time = driver_UP.find_elements(By.XPATH, "//*[@class='dp-time f-19 d-color f-bold']")
    end_time = driver_UP.find_elements(By.XPATH, "//*[@class='bp-time f-19 d-color disp-Inline']")
    total_duration = driver_UP.find_elements(By.XPATH, "//*[@class='dur l-color lh-24']")
    try:
        rating = driver_UP.find_elements(By.XPATH,"//div[@class='clearfix row-one']/div[@class='column-six p-right-10 w-10 fl']")
    except:
        continue
    price = driver_UP.find_elements(By.XPATH, '//*[@class="fare d-block"]')
    seats = driver_UP.find_elements(By.XPATH, "//div[contains(@class, 'seat-left')]")

    # Append data to respective lists
    for bus in bus_name:
        Bus_names_UP.append(bus.text)
        Route_links_UP.append(link)
        Route_names_UP.append(routes)
    for bus_type_elem in bus_type:
        Bus_types_UP.append(bus_type_elem.text)
    for start_time_elem in start_time:
        Start_Time_UP.append(start_time_elem.text)
    for end_time_elem in end_time:
        End_Time_UP.append(end_time_elem.text)
    for total_duration_elem in total_duration:
        Total_Duration_UP.append(total_duration_elem.text)
    for ratings in rating:
        Ratings_UP.append(ratings.text)
    for price_elem in price:
        Prices_UP.append(price_elem.text)
    for seats_elem in seats:
        Seats_Available_UP.append(seats_elem.text)
print("Successfully Completed")

Successfully Completed

In [620]:
# from list to convert data frame
data_UP = {
    'Route_name': Route_names_UP,
    'Route_link': Route_links_UP,
    'Bus_name': Bus_names_UP,
    'Bus_type': Bus_types_UP,
    'Start_time': Start_Time_UP,
    'Total_duration': Total_Duration_UP,
    'End_time': End_Time_UP,
    "Ratings":Ratings_UP,
    'Price': Prices_UP,
    "Seats_Available":Seats_Available_UP
    
}


df_buses_UP = pd.DataFrame(data_UP)
#convert dataframe to csv
path=r"C:\Users\M Karan kumar\1JupyterNoteBOOk\REDBUS\buses_UP.csv"
df_buses_UP.to_csv(path,index=False)

In [622]:
df_buses_UP

,Route_name,Route_link,Bus_name,Bus_type,Start_time,Total_duration,End_time,Ratings,Price,Seats_Available
0,Delhi to Bareilly,https://www.redbus.in/bus-tickets/delhi-to-bar...,UPSRTC - BLY0140,Janrath AC Seater 2+2,08:47,05h 43m,14:30,3.3\n3,INR 598,36 Seats available
1,Delhi to Bareilly,https://www.redbus.in/bus-tickets/delhi-to-bar...,UPSRTC - STD0071,Janrath AC Seater 2+2,09:02,06h 14m,15:16,4.4\n5,INR 598,35 Seats available
2,Delhi to Bareilly,https://www.redbus.in/bus-tickets/delhi-to-bar...,UPSRTC - KSB0085,Volvo AC Seater 2+2,09:31,05h 00m,14:31,3.3\n3,INR 844,39 Seats available
3,Delhi to Bareilly,https://www.redbus.in/bus-tickets/delhi-to-bar...,UPSRTC - RKD0845,Shatabdi AC Seater 2+2,10:05,05h 00m,15:05,3.3,INR 598,36 Seats available
4,Delhi to Bareilly,https://www.redbus.in/bus-tickets/delhi-to-bar...,UPSRTC - HPR0001,Ordinary Non AC Seater 2+3,10:20,05h 40m,16:00,3.3\n3,INR 444,52 Seats available
...,...,...,...,...,...,...,...,...,...,...
2388,Dehradun to Bareilly,https://www.redbus.in/bus-tickets/dehradun-to-...,UPSRTC - SJP0657,Ordinary Non AC Seater 2+3,14:30,08h 20m,22:50,3.3,INR 521,52 Seats available
2389,Dehradun to Bareilly,https://www.redbus.in/bus-tickets/dehradun-to-...,UPSRTC - RKD0057,Ordinary Non AC Seater 2+3,19:31,07h 29m,03:00,3.1\n4,INR 517,52 Seats available
2390,Dehradun to Bareilly,https://www.redbus.in/bus-tickets/dehradun-to-...,UPSRTC - RKD0135,Janrath AC Seater 2+3,22:31,07h 30m,06:01,2.3\n42,INR 652,47 Seats available
2391,Dehradun to Bareilly,https://www.redbus.in/bus-tickets/dehradun-to-...,Vijay Tour and Travels,A/C Seater / Sleeper (2+1),15:30,07h 40m,23:10,2.9\n17,1329,28 Seats available
2392,Dehradun to Bareilly,https://www.redbus.in/bus-tickets/dehradun-to-...,Mahalaxmi Travels,Bharat Benz A/C Seater /Sleeper (2+1),17:00,10h 00m,03:00,3.6,INR 599,26 Seats available

**10.WestBengal**

In [419]:
df_WB=pd.read_csv('WestBengal.csv')

In [421]:
df_WB

,Route_name,Route_link
0,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...
1,Durgapur to Calcutta,https://www.redbus.in/bus-tickets/durgapur-to-...
2,Digha to Calcutta,https://www.redbus.in/bus-tickets/digha-to-kol...
3,Kolkata to Digha,https://www.redbus.in/bus-tickets/kolkata-to-d...
4,Barasat (West Bengal) to Digha,https://www.redbus.in/bus-tickets/barasat-west...
5,Kolkata to Suri,https://www.redbus.in/bus-tickets/kolkata-to-suri
6,Barasat (West Bengal) to Midnapore,https://www.redbus.in/bus-tickets/barasat-west...
7,Midnapore to Kolkata,https://www.redbus.in/bus-tickets/midnapore-to...
8,Barasat (West Bengal) to Kolaghat,https://www.redbus.in/bus-tickets/barasat-west...
9,Barasat (West Bengal) to Contai (Kanthi),https://www.redbus.in/bus-tickets/barasat-west...
10,Habra to Digha,https://www.redbus.in/bus-tickets/habra-to-digha
11,Barasat (West Bengal) to Nandakumar (west bengal),https://www.redbus.in/bus-tickets/barasat-west...
12,Kolkata to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/kolkata-to-d...
13,Digha to Habra,https://www.redbus.in/bus-tickets/digha-to-habra
14,Midnapore to Barasat (West Bengal),https://www.redbus.in/bus-tickets/midnapore-to...
15,Kolkata to Bolpur (West Bengal),https://www.redbus.in/bus-tickets/kolkata-to-b...
16,Barasat (West Bengal) to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/barasat-west...
17,Barasat (West Bengal) to Heria,https://www.redbus.in/bus-tickets/barasat-west...
18,Haldia to Barasat (West Bengal),https://www.redbus.in/bus-tickets/haldia-to-ba...
19,Barasat (West Bengal) to Haldia,https://www.redbus.in/bus-tickets/barasat-west...
20,Haldia to Kolkata,https://www.redbus.in/bus-tickets/haldia-to-ko...
21,Barasat (West Bengal) to Debra,https://www.redbus.in/bus-tickets/barasat-west...
22,Barasat (West Bengal) to Burdwan,https://www.redbus.in/bus-tickets/barasat-west...
23,Kolkata to Bakkhali,https://www.redbus.in/bus-tickets/kolkata-to-b...
24,Kolkata to Purulia,https://www.redbus.in/bus-tickets/kolkata-to-p...
25,Durgapur (West Bengal) to Purulia,https://www.redbus.in/bus-tickets/durgapur-to-...
26,Habra to Midnapore,https://www.redbus.in/bus-tickets/habra-to-mid...
27,Kolkata to Asansol (West Bengal),https://www.redbus.in/bus-tickets/kolkata-to-a...
28,Durgapur (West Bengal) to Barasat (West Bengal),https://www.redbus.in/bus-tickets/durgapur-to-...
29,Barasat (West Bengal) to Asansol (West Bengal),https://www.redbus.in/bus-tickets/barasat-west...
30,Jayrambati (West Bengal) to Barasat (West Bengal),https://www.redbus.in/bus-tickets/jayrambati-w...
31,Kolkata to Haldia,https://www.redbus.in/bus-tickets/kolkata-to-h...
32,Habra to Durgapur (West Bengal),https://www.redbus.in/bus-tickets/habra-to-dur...
33,Habra to Nandakumar (west bengal),https://www.redbus.in/bus-tickets/habra-to-nan...
34,Habra to Kolaghat,https://www.redbus.in/bus-tickets/habra-to-kol...
35,Kolkata to Mayapur ISKCON,https://www.redbus.in/bus-tickets/kolkata-to-m...
36,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria
37,Midnapore to Kolkata Airport,https://www.redbus.in/bus-tickets/midnapore-to...

In [525]:
# retrive the bus details
driver_WB = webdriver.Chrome()
Bus_names_WB = []
Bus_types_WB = []
Start_Time_WB = []
End_Time_WB = []
Ratings_WB = []
Total_Duration_WB = []
Prices_WB = []
Seats_Available_WB = []
Route_names_WB = []
Route_links_WB = []

driver_WB.maximize_window()
for i,r in df_WB.iterrows():
    link=r["Route_link"]
    routes=r["Route_name"]
# Loop through each link
    driver_WB.get(link)
    time.sleep(6)  

    # Click on elements to reveal bus details
    elements = driver_WB.find_elements(By.XPATH, f"//a[contains(@href, '{link}')]")
    for element in elements:
        element.click()
        time.sleep(2) 

    try:
        clicks = driver_WB.find_element(By.XPATH, "//div[@class='button']")
        clicks.click()
    except:
        continue
        time.sleep(2)
         
        
    number_of_scrolls = 25
    scroll_pause_time = 1  # Adjust this based on the page's loading time

    for _ in range(number_of_scrolls):
        # Scroll down to the bottom using JavaScript
        driver_WB.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    
        # Wait for new content to load
        time.sleep(scroll_pause_time)

    # Extract bus details
    bus_name = driver_WB.find_elements(By.XPATH, "//div[@class='travels lh-24 f-bold d-color']")
    bus_type = driver_WB.find_elements(By.XPATH, "//div[@class='bus-type f-12 m-top-16 l-color evBus']")
    start_time = driver_WB.find_elements(By.XPATH, "//*[@class='dp-time f-19 d-color f-bold']")
    end_time = driver_WB.find_elements(By.XPATH, "//*[@class='bp-time f-19 d-color disp-Inline']")
    total_duration = driver_WB.find_elements(By.XPATH, "//*[@class='dur l-color lh-24']")
    try:
        rating = driver_WB.find_elements(By.XPATH,"//div[@class='clearfix row-one']/div[@class='column-six p-right-10 w-10 fl']")
    except:
        continue
    price = driver_WB.find_elements(By.XPATH, '//*[@class="fare d-block"]')
    seats = driver_WB.find_elements(By.XPATH, "//div[contains(@class, 'seat-left')]")

    # Append data to respective lists
    for bus in bus_name:
        Bus_names_WB.append(bus.text)
        Route_links_WB.append(link)
        Route_names_WB.append(routes)
    for bus_type_elem in bus_type:
        Bus_types_WB.append(bus_type_elem.text)
    for start_time_elem in start_time:
        Start_Time_WB.append(start_time_elem.text)
    for end_time_elem in end_time:
        End_Time_WB.append(end_time_elem.text)
    for total_duration_elem in total_duration:
        Total_Duration_WB.append(total_duration_elem.text)
    for ratings in rating:
        Ratings_WB.append(ratings.text)
    for price_elem in price:
        Prices_WB.append(price_elem.text)
    for seats_elem in seats:
        Seats_Available_WB.append(seats_elem.text)
print("Successfully Completed")

Successfully Completed

In [527]:
# from list to convert data frame
data_WB = {
    'Route_name': Route_names_WB,
    'Route_link': Route_links_WB,
    'Bus_name': Bus_names_WB,
    'Bus_type': Bus_types_WB,
    'Start_time': Start_Time_WB,
    'Total_duration': Total_Duration_WB,
    'End_time': End_Time_WB,
    "Ratings":Ratings_WB,
    'Price': Prices_WB,
    "Seats_Available":Seats_Available_WB,
}

df_buses_WB = pd.DataFrame(data_WB)
#convert dataframe to csv
path=r"C:\Users\M Karan kumar\1JupyterNoteBOOk\REDBUS\buses_WB.csv"
df_buses_WB.to_csv(path,index=False)

In [529]:
df_buses_WB

,Route_name,Route_link,Bus_name,Bus_type,Start_time,Total_duration,End_time,Ratings,Price,Seats_Available
0,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...,WBTC (CTC) HABRA-DIGHA via Esplanade - 176|04:00,Non AC Seater (2+3),04:00,05h 50m,09:50,4.0\n10,INR 165,30 Seats available
1,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...,WBTC (CTC) BARASAT-DIGHA via Bally - 38|05:40,Non AC Seater (2+3),05:40,04h 30m,10:10,3.4\n110,INR 161,29 Seats available
2,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...,WBTC (CTC) BADURIA - DIGHA via Bally - 155|09:00,Non AC Seater (2+3),09:00,03h 25m,12:25,3.4\n23,INR 161,37 Seats available
3,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...,WBTC (CTC) HABRA-DIGHA via Bally - 26|10:00,Non AC Seater (2+3),10:00,04h 45m,14:45,3.3\n49,INR 161,41 Seats available
4,Digha to Barasat (West Bengal),https://www.redbus.in/bus-tickets/digha-to-bar...,"WBTC (CTC) BARASAT-DIGHA via Esplanade, Karuna...",Non AC Seater (2+3),10:15,05h 20m,15:35,3.0\n4,INR 165,43 Seats available
...,...,...,...,...,...,...,...,...,...,...
574,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|03:45,Non AC Seater (2+3),03:45,03h 20m,07:05,2.4\n2,INR 130,8 Seats available
575,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|04:15,Non AC Seater (2+3),04:15,03h 20m,07:35,4.5\n4,INR 130,9 Seats available
576,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|05:15,Non AC Seater (2+3),05:15,03h 20m,08:35,2.9\n10,INR 130,23 Seats available
577,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|06:55,Non AC Seater (2+3),06:55,03h 50m,10:45,3.0\n1,INR 130,43 Seats available
578,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|12:45,Non AC Seater (2+3),12:45,03h 55m,16:40,3.7,INR 130,48 Seats available